name: Create Documents
on:
  push:
    paths:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PERSON: siamak_faal  # Who's CV is this?

    steps:
      - uses: actions/checkout@v4
      - name: Install libraries
        run: sudo apt-get install -y pandoc texlive
      - name: Generate Word doc
        run: pandoc ${{ env.PERSON }}.md -o ${{ env.PERSON }}.docx
      - name: Generate PDF
        run: pandoc ${{ env.PERSON }}.md -o ${{ env.PERSON }}.pdf

      # Step to configure git user
      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USER_NAME }}

      # Step to commit and push the generated files
      - name: Commit and Push
        run: |
          git add ${{ env.PERSON }}.pdf ${{ env.PERSON }}.docx
          git commit -m "Update CV documents for ${{ env.PERSON }}"
          git remote set-url origin https://siamakfaal:${{ secrets.GH_PAT }}@github.com/siamakfaal/curriculum-vitae.git
          git push
