name: Create Documents
on:
  push:
    paths:
      - 'siamak_faal.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install libraries
        run: |
          sudo apt-get install pandoc
          sudo apt-get install texlive
          mkdir cv
      - name: Generate Word doc
        run: pandoc siamak_faal.md -o cv/siamak_faal.docx
      - name: Generate PDF
        run: pandoc siamak_faal.md -o cv/siamak_faal.pdf

      - uses: actions/upload-artifact@v3
        with:
          name: siamak_faal_cv
          path: cv
