name: Create Documents
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install libraries
        run: |
          sudo apt-get install pandoc
          echo "Done!"
