name: Create Documents
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install libraries
        run: |
          sudo apt-get install pandoc
      - name: Generate Word doc
        run: pandoc siamak_faal.md -o siamak_faal.docx
